defaults:
  - default

# strategy: ddp # lightning native ddp with find_unused_parameters=False
strategy: ddp_find_unused_parameters_true # default: lightning native ddp with find_unused_parameters=True
# strategy: fsdp # fsdp
# strategy: deepspeed_stage_2 # deepspeed stage 2

accelerator: cuda
devices: 2
num_nodes: 1
sync_batchnorm: True
