# reasons you might want to use `environment.yaml` instead of `requirements.txt`:
# - pip installs packages in a loop, without ensuring dependencies across all packages
#   are fulfilled simultaneously, but conda achieves proper dependency control across
#   all packages
# - conda allows for installing packages without requiring certain compilers or
#   libraries to be available in the system, since it installs precompiled binaries

name: blindest

channels:
  - pytorch
  - conda-forge
  - defaults

# it is strongly recommended to specify versions of packages installed through conda
# to avoid situation when version-unspecified packages install their latest major
# versions which can sometimes break things

# current approach below keeps the dependencies in the same major versions across all
# users, but allows for different minor and patch versions of packages where backwards
# compatibility is usually guaranteed

dependencies:
  - pytorch=2.3.1
  - torchvision=0.18.*
  - torchaudio=2.3.*
  - lightning=2.*
  - torchmetrics=1.3.*
  - hydra-core=1.3.*
  - rich=13.*
  - pre-commit=3.*
  - pytest=7.*

  # --------- loggers --------- #
  - wandb
  - clearml
  # - neptune-client
  # - mlflow
  # - comet-ml
  # - aim>=3.16.2 # no lower than 3.16.2, see https://github.com/aimhubio/aim/issues/2550

  - pip>=23
  - pip:
      - hydra-optuna-sweeper==1.2.0
      - hydra-colorlog==1.2.0
      - rootutils
      - pre-commit      # hooks for applying linters on commit
      - rich            # beautiful text formatting in terminal
      - pytest          # tests
      - sh            # for running bash commands in some tests (linux/macos only)
      - einops         # for einops.einops
      - pandas
      - scikit-learn
      - librosa
      - cupy-cuda12x
      - transformers
      - xformers
      - deepspeed
      - nnAudio==0.3.2
      - pydmd
      - torch-dct
      - git+https://github.com/detly/gammatone.git
