jointRegressorModule:
  _target_: src.network.RpRegressor_baselineTAECNN.JointRegressorModuleBaselineTAECNN

  net:
    _target_: src.network.models.baselineTAECNN.TAECNN
    ch_in: 1
    ch_out: 2 # 2 for RapRegressor_baselineTAECNN, 4 for JointRegressor_baselineTAECNN
    max_length_sec: 20
    fs: 16000
    fc: 20
    dropout_prob: 0.4

  optimizer:
    _target_: torch.optim.RMSprop
    _partial_: true
    lr: 1e-3

  optim_cfg:
    Th_weight: 0.4
    Tt_weight: 0.6