


volumeRegressorModule:
  _target_: src.network.volumeRegressor_module_linear.VolumeRegressorModule

  net:
    _target_: src.network.models.roomFeatureEncoder.RoomEncoder
    ch_in: 128
    ch_out: 1
    num_layers: 8
    num_heads: 8
    embed_dim: 512
    ch_scale: 4
    dropout_prob: 0.1
    feat_type: "mfcc"
    decoder_type: "volume"


  optimizer:
    _target_: torch.optim.RAdam
    _partial_: true
    lr: 1e-4
    betas : [0.9, 0.98]
    eps: 1e-8
    weight_decay: 1e-6

  scheduler: 
    _target_: torch.optim.lr_scheduler.CosineAnnealingLR
    _partial_: true

  optim_cfg:
    T_max: 150



distSrcRegressorModule:
  _target_: src.network.distSrcRegressor_module_linear.DistSrcRegressorModule

  net:
    _target_: src.network.models.roomFeatureEncoder.RoomEncoder
    ch_in: 128
    ch_out: 1
    num_layers: 8
    num_heads: 8
    embed_dim: 512
    ch_scale: 4
    dropout_prob: 0.1
    feat_type: "mfcc"
    decoder_type: "distSrc"
    dist_src_est: true


  optimizer:
    _target_: torch.optim.RAdam
    _partial_: true
    lr: 1e-4
    betas : [0.9, 0.98]
    eps: 1e-8
    weight_decay: 1e-6

  scheduler: 
    _target_: torch.optim.lr_scheduler.CosineAnnealingLR
    _partial_: true

  optim_cfg:
    T_max: 220


jointRegressorModule:
  _target_: src.network.jointRegressor_module_encoder.JointRegressorModuleEncoder

  net:
    _target_: src.network.models.roomFeatureEncoder.RoomEncoder
    ch_in: 128
    ch_out: 1
    num_layers: 8
    num_heads: 8
    embed_dim: 512
    ch_scale: 4
    dropout_prob: 0.1
    feat_type: "mfcc"

  optimizer:
    _target_: torch.optim.RAdam
    _partial_: true
    lr: 1e-4
    betas : [0.9, 0.98]
    eps: 1e-8
    weight_decay: 1e-6

  scheduler:
    _target_: torch.optim.lr_scheduler.CosineAnnealingLR
    _partial_: true

  optim_cfg:
    sti_weight: 1.0
    alcons_weight: 1.0
    tr_weight: 1.0
    edt_weight: 1.0
    c80_weight: 1.0
    c50_weight: 1.0
    d50_weight: 1.0
    ts_weight: 1.0
    volume_weight: 1.0
    dist_src_weight: 1.0
    T_max: 300