jointRegressorModule:
  _target_: src.network.RpRegressor_baselineFullCNN_10params.JointRegressorModuleBaselineFullCNN

  net:
    _target_: src.network.models.baselineFullCNN.FullCNN
    ch_in: 1
    ch_out: 10
    n_fft_gammatone: 384
    n_bins_gammatone: 128
    hop_length_gammatone: 192
    dropout_prob: 0.5
    dist_src_est: False

  optimizer:
    _target_: torch.optim.Adam
    _partial_: true
    lr: 1e-3


