# @package _global_

defaults:
  - _self_
  - data: ReverbSpeech # "ReverbSpeechJoint", "ReverbSpeechBaseline", choose datamodule with `predict_dataloader()` for evaluation,
  - model: network
  - logger: wandb
  - trainer: default
  - paths: default
  - extras: default
  - hydra: default

task_name: "evaluation_joint"
# task_name: "evaluation_rir"
# task_name: "evaluation_volume"
# task_name: "evaluation_dist_src"
# task_name: "evaluation_ori_src"
# task_name: "evaluation_ori_src_woBC"
# task_name: "evaluation_numEst"
# task_name: "evaluation_roomEncoder"

tags: ["dev"]

# ! -------------------- joint estimation --------------------
# gammatonegram model for joint estimation
# ckpt_path: ${paths.root_dir}/logs/regression_ParametricPredictor_joint_est/runs/${time_stamp}/checkpoints/${epoch_num}.ckpt

# melspectrogram model for joint estimation
ckpt_path: ${paths.root_dir}/logs/regression_ParametricPredictor_joint_est/runs/${time_stamp}/checkpoints/${epoch_num}.ckpt

# MFCC model for joint estimation
# ckpt_path: ${paths.root_dir}/logs/regression_ParametricPredictor_joint_est/runs/${time_stamp}/checkpoints/${epoch_num}.ckpt

# Spectrogram model for joint estimation
# ckpt_path: ${paths.root_dir}/logs/regression_ParametricPredictor_joint_est/runs/${time_stamp}/checkpoints/${epoch_num}.ckpt

# ! -------------------- RIR estimation --------------------
# passing checkpoint path is necessary for prediction or evaluation
# MFCC model for RIR
# ckpt_path: ${paths.root_dir}/logs/regression_ParametricPredictor_RIR/runs/${time_stamp}/checkpoints/${epoch_num}.ckpt


# ! -------------------- volume estimation --------------------
# MFCC model for volume
# ckpt_path: ${paths.root_dir}/logs/regression_ParametricPredictor_volume/runs/${time_stamp}/checkpoints/${epoch_num}.ckpt


# ! -------------------- dist_src estimation --------------------
# MFCC model for dist_src
# ckpt_path: ${paths.root_dir}/logs/regression_ParametricPredictor_dist_src/runs/${time_stamp}/checkpoints/${epoch_num}.ckpt


# ! -------------------- ori_src estimation --------------------
# MFCC model for ori_src
# ckpt_path: ${paths.root_dir}/logs/regression_ParametricPredictor_ori_src/runs/${time_stamp}/checkpoints/${epoch_num}.ckpt


# ! -------------------- numEst estimation --------------------
# gammatonegram model for num of occupancy
# ckpt_path: ${paths.root_dir}/logs/classification_numOcc/runs/${time_stamp}/checkpoints/${epoch_num}.ckpt

# melspectrogram model for num of occupancy
# ckpt_path: ${paths.root_dir}/logs/classification_numOcc/runs/${time_stamp}/checkpoints/${epoch_num}.ckpt

# MFCC model for num of occupancy
# ckpt_path: ${paths.root_dir}/logs/classification_numOcc/runs/${time_stamp}/checkpoints/${epoch_num}.ckpt