# @package _global_

defaults:
  - _self_
  - data: ReverbSpeechJointEstE2EMixReal
  - model: network_e2e
  - logger: null
  - trainer: default
  - paths: default
  - extras: default
  - hydra: default

# task_name: "prediction_joint"
task_name: "prediction_joint_RP_realPart"
# task_name: "prediction_joint_RP_syntheticPart"
# task_name: "prediction_numEst"

tags: ["dev"]


# * -------------------- joint estimation --------------------
# gammatonegram model for joint estimation
# ckpt_path: ${paths.root_dir}/logs/regression_ParametricPredictor_joint_est/{run_id}/checkpoints/epoch_{epoch}.ckpt
# pred_path: ${paths.output_dir}/predictions_joint_gammatone.pt

# # melspectrogram model for joint estimation
# ckpt_path: ${paths.root_dir}/logs/regression_ParametricPredictor_joint_est/{run_id}/checkpoints/epoch_{epoch}.ckpt
# pred_path: ${paths.output_dir}/predictions_joint_mel.pt

# MFCC model for joint estimation
ckpt_path: ${paths.root_dir}/logs/regression_ParametricPredictor_joint_RAP_mixReal/{run_id}/checkpoints/epoch_{epoch}.ckpt
pred_path: ${paths.output_dir}/predictions_joint_mfcc.pt

# Spectrogram model for joint estimation
# ckpt_path: ${paths.root_dir}/logs/regression_ParametricPredictor_joint_est/runs/{run_id}/checkpoints/epoch_{epoch}.ckpt
# pred_path: ${paths.output_dir}/predictions_joint_spectrogram.pt


# * -------------------- numEst estimation --------------------
# gammatonegram model for num of occupancy
# ckpt_path: ${paths.root_dir}/logs/classification_numOcc/runs/{run_id}/checkpoints/epoch_{epoch}.ckpt
# pred_path: ${paths.output_dir}/predictions_numOcc_gammatone.pt

# melspectrogram model for num of occupancy
# ckpt_path: ${paths.root_dir}/logs/classification_numOcc/runs/{run_id}/checkpoints/epoch_{epoch}.ckpt
# pred_path: ${paths.output_dir}/predictions_numOcc_mel.pt

# MFCC model for num of occupancy
# ckpt_path: ${paths.root_dir}/logs/classification_numOcc/runs/{run_id}/checkpoints/epoch_{epoch}.ckpt
# pred_path: ${paths.output_dir}/predictions_numOcc_mfcc.pt

# Spectrogram model for num of occupancy
# ckpt_path: ${paths.root_dir}/logs/classification_numOcc/runs/{run_id}/checkpoints/epoch_{epoch}.ckpt
# pred_path: ${paths.output_dir}/predictions_numOcc_spectrogram.pt